version: '3.2'
services:
    las:
        image: sconecuratedimages/iexec:las
        devices:
         - "/dev/isgx"
        command: las
        tty: true
        ports:
          - target: 18766
            published: 18766
            protocol: tcp
            mode: host
